---
- name: Destroy servers.
  hosts: localhost
  connection: local
  gather_facts: false
  user: root
  vars: 
    hcloud_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"

  vars_files:
  - config.yml

  tasks:
  - name: Destroy servers.
    hcloud_server:
      api_token: "{{ hcloud_token }}"
      name: "{{ server_name }}"
      server_type: "{{ server_type }}"
      image: "{{ server_image }}"
      location: "{{ server_location }}"
      state: absent
      ssh_keys:
      - "{{ hcloud_ssh_key_name }}"
    register: server
    loop: "{{ server_names }}"
    loop_control:
      loop_var: server_name
