---
- name: Create servers.
  hosts: localhost
  connection: local
  gather_facts: false
  user: root
  vars:
    hcloud_token: "{{ lookup('env', 'HCLOUD_TOKEN') }}"
  
  vars_files:
  - config.yml

  pre_tasks:
  - name: Create servers.
    hcloud_server:
      api_token: "{{ hcloud_token }}"
      name: "{{ server_name }}"
      server_type: "{{ server_type }}"
      image: "{{ server_image }}"
      location: "{{ server_location }}"
      state: present
      ssh_keys:
      - "{{ hcloud_ssh_key_name }}"
    register: server
    loop: "{{ server_names }}"
    loop_control:
      loop_var: server_name
  
  - name: Refresh inventory after adding servers.
    meta: refresh_inventory
  
  - name: Remove host keys of servers.
    known_hosts:
      name: "{{ item.hcloud_server.ipv4_address }}"
      path: /home/nikolai/.ssh/known_hosts
      state: absent
    loop: "{{ server.results }}"

- name: Setup docker on servers.
  hosts: all
  user: root
  gather_facts: false
  vars_files:
  - config.yml

  pre_tasks:
  - name: Wait until servers are ready.
    wait_for:
      host: "{{ ipv4 }}"
      port: 22
      search_regex: OpenSSH
      delay: 2
      timeout: 320
    delegate_to: localhost
  
  tasks:
  - import_tasks: tasks/install-docker.yml

  - name: "Create user {{ username }}."
    user:
      name: "{{ username }}"
      password: "{{ password | password_hash('sha512') }}"
      groups: sudo,docker
      append: true
